services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8123"
    environment:
      - LOVELACE_LOCAL_FILES=my-custom-card.js
    volumes:
      - ./config:/config
      - ./workspace:/config/www/workspace
